name: CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checking out the affected branch...
        uses: actions/checkout@v2
      - name: Setting the GitHub Action user in git configuration...
        uses: fregante/setup-git-user@v1
      - name: Checking packages to see what changed...
        uses: dorny/paths-filter@v2.10.2
        id: changes
        with:
          filters: |
            angular:
              - 'packages/angular/**'
            base:
              - 'packages/base/**'
            cli:
              - 'packages/cli/**'
            react:
              - 'packages/react/**'
            react-native:
              - 'packages/react-native/**'
            svelte:
              - 'packages/svelte/**'
            vanilla:
              - 'packages/vanilla/**'
            vue:
              - 'packages/vue/**'
            web:
              - 'apps/web/**'
      - name: Setting up Node.js LTS v16...
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Restoring dependencies...
        uses: actions/cache@v2
        with:
          path: node_modules
          key: modules-${{ hashFiles('yarn.lock') }}
      - name: Installing dependencies...
        if: steps.cache-web-app.outputs.cache-hit != 'true' || steps.cache-angular-package.outputs.cache-hit != 'true' || steps.cache-base-package.outputs.cache-hit != 'true' || steps.cache-cli-package.outputs.cache-hit != 'true' || steps.cache-react-package.outputs.cache-hit != 'true' || steps.cache-react-native-package.outputs.cache-hit != 'true' || steps.cache-svelte-package.outputs.cache-hit != 'true' || steps.cache-vanilla-package.outputs.cache-hit != 'true' || steps.cache-vue-package.outputs.cache-hit != 'true' 
        run: yarn
      - name: Publishing the affected packages...
        run: |
          cd scripts/bash
          chmod +x ./publish.sh
          if [[ ${{ steps.changes.outputs.angular }} == 'true' ]] || [[ ${{ steps.changes.outputs.base }} == 'true' ]] || [[ ${{ steps.changes.outputs.cli }} == 'true' ]] || [[ ${{ steps.changes.outputs.react }} == 'true' ]] || [[ ${{ steps.changes.outputs.react-native }} == 'true' ]] || [[ ${{ steps.changes.outputs.svelte }} == 'true' ]] || [[ ${{ steps.changes.outputs.vanilla }} == 'true' ]] || [[ ${{ steps.changes.outputs.vue }} == 'true' ]]
          then
            ./publish.sh packages
          fi
          if [[ ${{ steps.changes.outputs.web }} == 'true' ]]
          then
            ./publish.sh web
          fi
